const U = 'up';
const D = 'down';
const L = 'left';
const R = 'right';

export const LEVELS = [
  {
    id: 'level-1',
    difficulty: 1,
    name: '第一关：白木乃伊的追猎',
    tiles: [
      '#######',
      '#.#W..#',
      '#.....#',
      '#..##E#',
      '#.#.#.#',
      '#P....#',
      '#######',
    ],
    monsters: [],
    doorsOpen: false,
    solution: [U, D, R, R, R, R, U, U],
  },
  {
    id: 'level-2',
    difficulty: 2,
    name: '第二关：红色死角',
    tiles: [
      '#######',
      '#.#.#R#',
      '#T...E#',
      '#..#..#',
      '#.#...#',
      '#..P..#',
      '#######',
    ],
    monsters: [],
    doorsOpen: false,
    solution: [L, L, U, U, D, U, R, U, R, R, R],
  },
  {
    id: 'level-3',
    difficulty: 3,
    name: '第三关：蝎子与钥匙',
    tiles: [
      '#########',
      '#.####.##',
      '#S.....T#',
      '#....#.P#',
      '#.##....#',
      '##K.....#',
      '###.#.###',
      '#EG...#.#',
      '#########',
    ],
    monsters: [],
    doorsOpen: false,
    solution: [D, D, L, L, L, L, L, R, D, D, L, L],
  },
  {
    id: 'level-4',
    difficulty: 4,
    name: '第四关：双面追击',
    tiles: [
      '#########',
      '#W...E#.#',
      '##G##..R#',
      '#...##..#',
      '#.##....#',
      '#K..#.#T#',
      '#.#P.#..#',
      '#.##....#',
      '#########',
    ],
    monsters: [],
    doorsOpen: false,
    solution: [
      U, L, L, U, D, R, R, D, R, D, R, R, L, L,
      U, L, U, L, L, U, U, R, U, U, R, R, R,
    ],
  },
  {
    id: 'level-5',
    difficulty: 5,
    name: '第五关：三方围猎',
    tiles: [
      '#########',
      '#.#...#.#',
      '#.###...#',
      '#..#.#..#',
      '#.#..#P.#',
      '##ST....#',
      '#.T.#.G.#',
      '##ERW.K##',
      '#########',
    ],
    monsters: [],
    doorsOpen: false,
    solution: [
      U, U, L, U, L, L, R, R, D, R, D, D, D, D, D, L, L, L, L,
    ],
  },
  {
    id: 'level-6',
    difficulty: 6,
    name: '第六关：金字塔深处',
    tiles: [
      '#########',
      '#S.E...W#',
      '#.G#...W#',
      '##..#...#',
      '#.#K##..#',
      '#.#...###',
      '#...#.TT#',
      '#P.#....#',
      '#########',
    ],
    monsters: [],
    doorsOpen: false,
    solution: [
      R, U, R, U, R, R, D, D, R, L, U, U, L, L, U, U, L, U, U, R,
    ],
  },
];
